package fr.isen.m1.cyber.r2ddoc

enum class Abbreviations(
    val word: String,
    val abbr: String
) {
    ALL("Allée", "ALL"),
    BD("Boulevard", "BD"),
    CCAL("Centre commercial", "CCAL"),
    IMP("Impasse", "IMP"),
    LOT("Lotissement", "LOT"),
    PL("Place", "PL"),
    RPT("Rond-point", "RPT"),
    SQ("Square", "SQ"),
    ZA("Zone d’activité", "ZA"),
    ZAC("Zone d’aménagement concerté", "ZAC"),
    AV("Avenue", "AV"),
    CTRE("Centre", "CTRE"),
    IMM("Immeuble(s)", "IMM"),
    LD("Lieu-dit", "LD"),
    PAS("Passag", "PAS"),
    RES("Résidence", "RES"),
    RTE("Route", "RTE"),
    VLGE("Village", "VLGE"),
    ZI("Zone Industrielle", "ZI"),
    ZAD("Zone d’aménagement différé", "ZAD"),
    ADJ("Adjudant", "ADJ"),
    AERG("Aérogare", "AERG"),
    AERP("Aéroport", "AERP"),
    AGRIC("Agricole", "AGRIC"),
    APP("Appartement(s)", "APP"),
    AERD("Aérodrome", "AERD"),
    AERN("Aéronautique", "AERN"),
    AGCE("Agence", "AGCE"),
    ANC("Ancien(nement)", "ANC"),
    ARMT("Armement", "ARMT"),
    ARR("Arrondissement", "ARR"),
    ASSOC("Association", "ASSOC"),
    AT("Atelier", "AT"),
    BAS("Bas(se, ses)", "BAS"),
    BAT("Bâtiment(s)", "BAT"),
    BP("Boîte Postale", "BP"),
    CANT("Canton", "CANT"),
    CP("Case Postale", "CP"),
    CTD("Citadelle", "CTD"),
    CNL("Colonel", "CNL"),
    CTE("Comité", "CTE"),
    CIAL("Commercial", "CIAL"),
    CIE("Compagnie", "CIE"),
    COOP("Coopérative", "COOP"),
    CRX("Croix", "CRX"),
    DEP("Départemental(aux)", "DEP"),
    DIV("Division", "DIV"),
    ECO("Economie(ique)", "ECO"),
    ENST("Enseignement", "ENST"),
    ENT("Entrée(s)", "ENT"),
    EP("Epoux(se)", "EP"),
    ETG("Etage", "ETG"),
    EVQ("Evêque", "EVQ"),
    FOR("Forêt (Forestier)", "FOR"),
    FUS("Fusilier", "FUS"),
    GAL("Général", "GAL"),
    GOU("Gouverneur", "GOU"),
    GDE("Grande", "GDE"),
    GDS("Grands", "GDS"),
    HTE("Haute", "HTE"),
    HTS("Hauts", "HTS"),
    HOSP("Hospice (Hospitalier)", "HOSP"),
    INFANT("Infanterie", "INFANT"),
    ING("Ingénieur", "ING"),
    INST("Institut", "INST"),
    LABO("Laboratoire", "LABO"),
    LTDV("Lieutenant de Vaisseau", "LTDV"),
    ASP("Aspirant", "ASP"),
    ASSUR("Assurance", "ASSUR"),
    BRQ("Baraquement", "BRQ"),
    BTN("Bataillon(s)", "BTN"),
    B("Bis", "B"),
    CAB("Cabinet", "CAB"),
    CDL("Cardinal", "CDL"),
    CHBR("Chambre", "CHBR"),
    COLL("Collège", "COLL"),
    COLO("Colonie", "COLO"),
    CDT("Commandant", "CDT"),
    COMM("Commune(al, aux)", "COMM"),
    COMP("Compagnon(s)", "COMP"),
    CS("Course Spéciale", "CS"),
    DELEG("Délégation", "DELEG"),
    DIR("Directeur(ction)", "DIR"),
    DR("Docteur", "DR"),
    ECRIV("Ecrivain(s)", "ECRIV"),
    ENS("Ensemble", "ENS"),
    ENTR("Entreprise", "ENTR"),
    ETS("Etablissement", "ETS"),
    EM("Etat Major", "EM"),
    FR("Faculté FAC Français (e)", "FR"),
    GEND("Gendarmerie", "GEND"),
    GOUV("Gouvernemental", "GOUV"),
    GD("Grand", "GD"),
    GDES("Grandes", "GDES"),
    HT("Haut", "HT"),
    HTES("Hautes", "HTES"),
    HOP("Hôpital (aux)", "HOP"),
    HOT("Hôtel", "HOT"),
    INF("Inférieur (e)", "INF"),
    INSP("Inspecteur", "INSP"),
    INTERN("International (e)", "INTERN"),
    LT("Lieutenant", "LT"),
    MME("Madame", "MME"),
    MAG("Magasin", "MAG"),
    ME("Maître", "ME"),
    MAR("Maritime", "MAR"),
    MMES("Mesdames", "MMES"),
    MM("Messieurs", "MM"),
    MLLE("Mademoiselle", "MLLE"),
    MAIS("Maison", "MAIS"),
    MAL("Maréchal", "MAL"),
    MED("Médecin (Médical)", "MED"),
    MLLS("Mesdemoiselles", "MLLES"),
    MIL("Militaire", "MIL"),
    MGR("Monseigneur", "MGR"),
    MIN("Ministère", "MIN"),
    M("Monsieur", "M"),
    MUN("Municipal", "MUN"),
    NAL("National", "NAL"),
    NOUV("Nouveau (elle)", "NOUV"),
    PAST("Pasteur", "PAST"),
    PTE("Petite", "PTE"),
    PTS("Petits", "PTS"),
    PREF("Préfet (préfecture)", "PREF"),
    PR("Professeur", "PR"),
    PROL("Prolongé (e)", "PROL"),
    Q("Quater", "Q"),
    RECT("Recteur", "RECT"),
    REG("Régional (e)", "REG"),
    REST("Restaurant", "REST"),
    STE("Sainte", "STE"),
    STS("Saints", "STS"),
    SGT("Sergent", "SGT"),
    SOC("Société", "SOC"),
    SPREF("Sous-préfet (Sous- SPREF préfecture)", "SPREF"),
    MUT("Mutuel", "MUT"),
    ND("Notre Dame", "ND"),
    OBS("Observatoire", "OBS"),
    PT("Petit", "PT"),
    PTES("Petites", "PTES"),
    POL("Police", "POL"),
    PDT("Président", "PDT"),
    PROF("Professionnel (le)", "PROF"),
    PROP("Propriété", "PROP"),
    C("Quinquies", "C"),
    RGT("Régiment", "RGT"),
    REP("République", "REP"),
    ST("Saint", "ST"),
    STES("Saintes", "STES"),
    SANA("Sanatorium", "SANA"),
    SCE("Service", "SCE"),
    SC("Sous couvert", "SC"),
    SUP("Supérieur (e)", "SUP"),
    TECH("Technicien(que)", "TECH"),
    TSA("Tri Service Armée", "TSA"),
    UNVT("Universitaire", "UNVT"),
    VELOD("Vélodrome", "VELOD"),
    VIEL("Vielle(s)", "VIEL"),
    SYND("Syndicat", "SYND"),
    T("Ter", "T"),
    TUN("Tunnel", "TUN"),
    UNIV("Université", "UNIV"),
    VVE("Veuve", "VVE"),
    VX("Vieux", "VX");

    companion object {
        private val supportedAbbreviations: List<Abbreviations>
            get() = values().toList()

        fun getAbbreviation(abbr: String): Abbreviations? {
            supportedAbbreviations.forEach {
                if (it.abbr == abbr) {
                    return it
                }
            }
            return null
        }

        fun getAbbreviations(): List<String> {
            return supportedAbbreviations.map { it.abbr }
        }

        fun getWords(): List<String> {
            return supportedAbbreviations.map { it.word }
        }
    }
}