package fr.isen.m1.cyber.r2ddoc

// -1 for max size means none
enum class DataValueIso20022(
    val id: String,
    val label: String,
    val minSize: Int,
    val maxSize: Int
) {
    ID_01("01", "Identifiant unique du document", 0, -1),
    ID_02("02", "Catégorie de document", 0, -1),
    ID_03("03", "Sous-catégorie de document", 0, -1),
    ID_04("04", "Application de composition", 0, -1),
    ID_05("05", "Version de l’application de composition", 0, -1),
    ID_06("06", "Date de l’association entre le document et le code 2D-Doc.", 6, 6),
    ID_07("07", "Heure de l’association entre le document et le code 2D-Doc.", 6, 6),
    ID_08("08", "Date d’expiration du document", 4, 4),
    ID_09("09", "Nombre de page du document", 4, 4),
    ID_0A("0A", "Editeur du 2D-Doc", 9, 9),
    ID_0B("0B", "Intégrateur du 2D-Doc", 9, 9),
    ID_0C("0C", "URL du document", 0, -1),
    ID_10("10", "Ligne 1 de la norme adresse postale :", 0, 38),
    ID_11("11", "Qualité de la personne bénéficiaire de la prestation", 0, 38),
    ID_12("12", "Prénom de la personne bénéficiaire de la prestation", 0, 38),
    ID_13("13", "Nom de la personne bénéficiaire de la prestation", 0, 38),
    ID_14("14", "Ligne 1 de la norme adresse postale: ", 0, 38),
    ID_15("15", "Qualité de la personne destinataire de la facture", 0, 38),
    ID_16("16", "Prénom de la personne destinataire de la facture", 0, 38),
    ID_17("17", "Nom de la personne destinataire de la facture", 0, 38),
    ID_18("18", "Numéro de facture", 0, -1),
    ID_19("19", "Numéro de client", 0, -1),
    ID_1A("1A", "Numéro du contrat", 0, -1),
    ID_1B("1B", "Identifiant du souscripteur du contrat", 0, -1),
    ID_1C("1C", "Date d’effet du contrat", 8, 8),
    ID_1D("1D", "Montant de la facture", 0, 16),
    ID_1E("1E", "Numéro de téléphone du bénéficiaire de la prestation", 0, 30),
    ID_1F("1F", "Numéro de téléphone du destinataire de la facture", 0, 30),
    ID_1G("1G", "Présence d’un co-bénéficiaire de la prestation non mentionné dans le code", 1, 1),
    ID_1H("1H", "Présence d’un co-destinataire de la facture non mentionné dans le code", 1, 1),
    ID_1I("1I", "Ligne 1 de la norme adresse postale du co-bénéficiaire de la prestation.", 0, 38),
    ID_1J("1J", "Qualité et/ou titre du co-bénéficiaire de la prestation.", 0, 38),
    ID_1K("1K", "Prénom du co-bénéficiaire de la prestation.", 0, 38),
    ID_1L("1L", "Nom du co-bénéficiaire de la prestation.", 0, 38),
    ID_1M("1M", "Ligne 1 de la norme adresse postale du co-destinataire de la facture.", 0, 38),
    ID_1N("1N", "Qualité et/ou titre du co-destinataire de la facture.", 0, 38),
    ID_1O("1O", "Prénom du co-destinataire de la facture.", 0, 38),
    ID_1P("1P", "Nom du co-destinataire de la facture.", 0, 38),
    ID_20("20", "Ligne 2 de la norme adresse postale du point de service des prestations :", 0, 38),
    ID_21("21", "Ligne 3 de la norme adresse postale du point de service des prestations :", 0, 38),
    ID_22("22", "Ligne 4 de la norme adresse postale du point de service des prestations :", 0, 38),
    ID_23("23", "Ligne 5 de la norme adresse postale du point de service des prestations :", 0, 38),
    ID_24("24", "Code postal ou code cedex du point de service des prestations", 5, 5),
    ID_25("25", "Localité de destination ou libellé cedex du point de service des prestations ", 0, 32),
    ID_26("26", "Pays de service des prestations", 2, 2),
    ID_27("27", "Ligne 2 de la norme adresse postale du destinataire de la facture", 0, 38),
    ID_28("28", "Ligne 3 de la norme adresse postale du destinataire de la facture", 0, 38),
    ID_29("29", "Numéro dans la voie + type et nom de la voie (Ligne 4 de la norme adresse postale) du destinataire de la facture", 0, 38),
    ID_2A("2A", "Mention de distribution (BP) suivie du libellé de la localité de destination", 0, 38),
    ID_2B("2B", "Code postal ou code cedex du destinataire de la facture", 5, 5),
    ID_2C("2C", "Localité de destination ou libellé cedex du destinataire de la facture", 0, 32),
    ID_2D("2D", "Pays du destinataire de la facture", 2, 2),
    ID_30("30", "Qualité Nom et Prénom", 0, 140),
    ID_31("31", "Code IBAN", 14, 38),
    ID_32("32", "Code BIC/SWIFT", 8, 11),
    ID_33("33", "Code BBAN", 0, 30),
    ID_34("34", "Pays de localisation du compte", 2, 2),
    ID_35("35", "Identifiant SEPAmail (QXBAN)", 14, 34),
    ID_36("36", "Date de début de période", 4, 4),
    ID_37("37", "Date de fin de période", 4, 4),
    ID_38("38", "Solde compte courant début de période", 0, 11),
    ID_39("39", "Solde compte courant fin de période", 0, 11),
    ID_40("40", "Numéro fiscal", 13, 13),
    ID_41("41", "Revenu fiscal de référence", 0, -1),
    ID_42("42", "Situation du foyer", 0, -1),
    ID_43("43", "Nombre de parts", 0, -1),
    ID_44("44", "Référence d’avis d’impôt", 13, 13),
    ID_50("50", "SIRET de l’employeur", 14, 14),
    ID_51("51", "Nombre d’heures travaillées", 6, 6),
    ID_52("52", "Cumul du nombre d’heures travaillées", 7, 7),
    ID_53("53", "Début de période", 4, 4),
    ID_54("54", "Fin de période", 4, 4),
    ID_55("55", "Date de début de contrat", 8, 8),
    ID_56("56", "Date de fin de contrat", 4, 4),
    ID_57("57", "Date de signature du contrat", 8, 8),
    ID_58("58", "Salaire net imposable", 0, 11),
    ID_59("59", "Cumul du salaire net imposable", 0, 12),
    ID_5A("5A", "Salaire brut du mois", 0, 11),
    ID_5B("5B", "Cumul du salaire brut", 0, 12),
    ID_5C("5C", "Salaire net", 0, 11),
    ID_5D("5D", "Ligne 2 de la norme adresse postale de l’employeur", 0, 38),
    ID_5E("5E", "Ligne 3 de la norme adresse postale de l’employeur", 0, 38),
    ID_5F("5F", "Numéro dans la voie + type et nom de la voie (Ligne 4 de la norme adresse postale) de l’employeur", 0, 38),
    ID_5G("5G", "Mention de distribution (BP) suivie du libellé de la localité de destination", 0, 38),
    ID_5H("5H", "Code postal ou code cedex de l’employeur (compris dans la ligne 6 de la norme adresse postale)", 5, 5),
    ID_5I("5I", "Localité de destination ou libellé cedex de l’employeur (compris dans la ligne 6 de la norme adresse postale)", 0, 32),
    ID_5J("5J", "Pays de l’employeur", 2, 2),
    ID_5K("5K", "Identifiant Cotisant Prestations Sociales", 0, 50),
    ID_60("60", "Liste des prénoms", 0, 60),
    ID_61("61", "Prénom", 0, 20),
    ID_62("62", "Nom patronymique", 0, 38),
    ID_63("63", "Nom d’usage", 0, 38),
    ID_64("64", "Nom d’épouse/époux", 0, 38),
    ID_65("65", "Type de pièce d’identité", 2, 2),
    ID_66("66", "Numéro de la pièce d’identité", 0, 20),
    ID_67("67", "Nationalité", 2, 2),
    ID_68("68", "Genre", 1, 1),
    ID_69("69", "Date de naissance", 8, 8),
    ID_6A("6A", "Lieu de naissance", 0, 32),
    ID_6B("6B", "Département du bureau émetteur", 3, 3),
    ID_6C("6C", "Pays de naissance", 2, 2),
    ID_6D("6D", "Nom et prénom du père. L’utilisation du séparateur ‘/’ est possible pour séparer le nom du prénom.", 0, 60),
    ID_6E("6E", "Nom et prénom de la mère. L’utilisation du séparateur ‘/’ est possible pour séparer le nom du prénom.", 0, 60),
    ID_6F("6F", "Machine Readable Zone (Zone de Lecture Automatique, ZLA)", 0, 90),
    ID_6G("6G", "Nom", 1, 38),
    ID_6H("6H", "Civilité", 1, 10),
    ID_6I("6I", "Pays émetteur", 2, 2),
    ID_6J("6J", "Type de document étranger", 1, 1),
    ID_6K("6K", "Numéro de la demande de document étranger", 19, 19),
    ID_6L("6L", "Date de dépôt de la demande", 8, 8),
    ID_6M("6M", "Catégorie du titre", 0, 40),
    ID_6N("6N", "Date de début de validité", 8, 8),
    ID_6O("6O", "Date de fin de validité", 8, 8),
    ID_6P("6P", "Autorisation", 0, 40),
    ID_6Q("6Q", "Numéro d’étranger", 0, 10),
    ID_6R("6R", "Numéro de visa", 12, 12),
    ID_6S("6S", "Ligne 2 de l’adresse postale du domicile", 0, 38),
    ID_6T("6T", "Ligne 3 de l’adresse postale du domicile", 0, 38),
    ID_6U("6U", "Ligne 4 de l’adresse postale du domicile", 0, 38),
    ID_6V("6V", "Ligne 5 de l’adresse postale du domicile", 0, 38),
    ID_6W("6W", "Code postal ou code cedex de l’adresse postale du domicile", 5, 5),
    ID_6X("6X", "Commune de l’adresse postale du domicile", 0, 32),
    ID_6Y("6Y", "Code pays de l’adresse postale du domicile", 2, 2),
    ID_70("70", "Date et heure du décès", 12, 12),
    ID_71("71", "Date et heure du constat de décès", 12, 12),
    ID_72("72", "Nom du défunt", 0, 38),
    ID_73("73", "Prénoms du défunt", 0, 60),
    ID_74("74", "Nom de jeune fille du défunt", 0, 38),
    ID_75("75", "Date de naissance du défunt", 8, 8),
    ID_76("76", "Genre du défunt", 1, 1),
    ID_77("77", "Commune de décès", 0, 45),
    ID_78("78", "Code postal de la commune de décès", 5, 5),
    ID_79("79", "Adresse du domicile du défunt", 0, 114),
    ID_7A("7A", "Code postal du domicile du défunt", 5, 5),
    ID_7B("7B", "Commune du domicile du défunt", 0, 45),
    ID_7C("7C", "Obstacle médico-légal", 1, 1),
    ID_7D("7D", "Mise en bière", 1, 1),
    ID_7E("7E", "Obstacle aux soins de conservation", 1, 1),
    ID_7F("7F", "Obstacle aux dons du corps", 1, 1),
    ID_7G("7G", "Recherche de la cause du décès", 1, 1),
    ID_7H("7H", "Délai de transport du corps", 2, 2),
    ID_7I("7I", "Prothèse avec pile", 1, 1),
    ID_7J("7J", "Retrait de la pile de prothèse", 1, 1),
    ID_7K("7K", "Code NNC", 13, 13),
    ID_7L("7L", "Code Finess de l'organisme agréé", 9, 9),
    ID_7M("7M", "Identification du médecin", 0, 64),
    ID_7N("7N", "Lieu de validation du certificat de décès", 0, 128),
    ID_7O("7O", "Certificat de décès supplémentaire", 1, 1),
    ID_80("80", "Nom", 0, 38),
    ID_81("81", "Prénoms", 0, 60),
    ID_82("82", "Numéro de carte", 0, 20),
    ID_83("83", "Organisme de tutelle", 0, 40),
    ID_84("84", "Profession", 0, 40),
    ID_90("90", "Identité de l'huissier de justice", 0, 38),
    ID_91("91", "Identité ou raison sociale du demandeur", 0, 38),
    ID_92("92", "Identité ou raison sociale du destinataire", 0, 38),
    ID_93("93", "Identité ou raison sociale de tiers concerné", 0, 38),
    ID_94("94", "Intitulé de l'acte", 0, 38),
    ID_95("95", "Numéro de l'acte", 0, 18),
    ID_96("96", "Date de signature de l'acte", 8, 8),
    ID_A0("A0", "Pays ayant émis l’immatriculation du véhicule.", 2, 2),
    ID_A1("A1", "Immatriculation du véhicule", 0, 17),
    ID_A2("A2", "Marque du véhicule.", 0, 17),
    ID_A3("A3", "Nom commercial du véhicule.", 0, 17),
    ID_A4("A4", "Numéro de série du véhicule (VIN).", 17, 17),
    ID_A5("A5", "Catégorie du véhicule.", 3, 3),
    ID_A6("A6", "Carburant.", 2, 2),
    ID_A7("A7", "Taux d’émission de CO2 du véhicule (en g/km).", 3, 3),
    ID_A8("A8", "Indication de la classe environnementale de réception CE.", 0, 12),
    ID_A9("A9", "Classe d’émission polluante.", 3, 3),
    ID_AA("AA", "Date de première immatriculation du véhicule.", 8, 8),
    ID_AB("AB", "Type de lettre", 0, 8),
    ID_AC("AC", "N° Dossier", 0, 19),
    ID_AD("AD", "Date Infraction", 4, 4),
    ID_AE("AE", "Heure de l’infraction", 4, 4),
    ID_AF("AF", "Nombre de points retirés lors de l’infraction", 1, 1),
    ID_AG("AG", "Solde de points", 1, 1),
    ID_AH("AH", "Numéro de la carte", 0, 30),
    ID_AI("AI", "Date d’expiration initiale", 8, 8),
    ID_AJ("AJ", "Numéro EVTC", 13, 13),
    ID_AK("AK", "Numéro de macaron", 7, 7),
    ID_AL("AL", "Numéro de la carte", 11, 11),
    ID_AM("AM", "Motif de sur-classement", 0, 5),
    ID_AN("AN", "Kilométrage", 8, 8),
    ID_B0("B0", "Liste des prénoms", 0, 60),
    ID_B1("B1", "Prénom", 0, 20),
    ID_B2("B2", "Nom patronymique", 0, 38),
    ID_B3("B3", "Nom d'usage", 0, 38),
    ID_B4("B4", "Nom d'épouse/époux", 0, 38),
    ID_B5("B5", "Nationalité Country", 2, 2),
    ID_B6("B6", "Genre", 1, 1),
    ID_B7("B7", "Date de naissance", 8, 8),
    ID_B8("B8", "Lieu de naissance", 0, 32),
    ID_B9("B9", "Pays de naissance", 2, 2),
    ID_BA("BA", "Mention obtenue", 1, 1),
    ID_BB("BB", "Numéro ou code d'identification de l'étudiant", 0, 50),
    ID_BC("BC", "Numéro du diplôme", 0, 20),
    ID_BD("BD", "Niveau du diplôme selon la classification CEC", 1, 1),
    ID_BE("BE", "Crédits ECTS obtenus", 3, 3),
    ID_BF("BF", "Année universitaire", 3, 3),
    ID_BG("BG", "Type de diplôme", 2, 2),
    ID_BH("BH", "Domaine", 0, 30),
    ID_BI("BI", "Mention", 0, 30),
    ID_BJ("BJ", "Spécialité", 0, 30),
    ID_BK("BK", "Numéro de l'Attestation de versement de la CVE", 14, 14),
    ID_C0("C0", "Genre du vendeur", 1, 1),
    ID_C1("C1", "Nom patronymique du vendeur", 0, 38),
    ID_C2("C2", "Prénom du vendeur", 0, 20),
    ID_C3("C3", "Date et heure de la cession", 12, 12),
    ID_C4("C4", "Date de la signature du vendeur", 8, 8),
    ID_C5("C5", "Genre de l’acheteur", 1, 1),
    ID_C6("C6", "Nom patronymique de l’acheteur", 0, 38),
    ID_C7("C7", "Prénom de l’acheteur", 0, 20),
    ID_C8("C8", "Ligne 4 de la norme adresse postale du domicile de l’acheteur", 0, 38),
    ID_C9("C9", "Code postal ou code cedex du domicile de l’acheteur", 5, 5),
    ID_CA("CA", "Commune du domicile de l’acheteur", 0, 45),
    ID_CB("CB", "N° d’enregistrement", 10, 10),
    ID_CC("CC", "Date et heure d'enregistrement dans le SIV", 12, 12);

    companion object {
        private val supportedValues: List<DataValueIso20022>
            get() = values().toList()

        fun getValue(id: String): DataValueIso20022? {
            supportedValues.forEach {
                if (it.id == id) {
                    return it
                }
            }
            return null
        }

        fun getIds(): List<String> {
            return supportedValues.map { it.id }
        }

        fun getLabels(): List<String> {
            return supportedValues.map { it.label }
        }
    }
}
